services:
  # backend:
  #   image: yara
  #   ports:
  #     - 3000:3000
  #   environment:
  #     DATABASE_URL: 'postgresql://yaraAdmin:yaraPasspass@db:5432/yara?schema=public'
  #   networks:
  #     - backend
  #     - frontend
  #   depends_on:
  #     - db

  # frontend:
  #   image: yara-web
  #   ports:
  #     - 3001:3001
  #   environment:
  #     BACKEND_URL: 'http://backend:3000'
  #   networks:
  #     - frontend

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: yaraPasspass
      POSTGRES_USER: yaraAdmin
      POSTGRES_DB: yara
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
